version: 2.1

executors:
  golang:
    docker:
      - image: circleci/golang:1.13-buster
    working_directory: ~/project

repo_cache_key: &repo_cache_key
  go-mod-{{ checksum "go.sum" }}.0


jobs:
  prepare:
    executor: golang
    steps:
      - checkout
      - restore_cache:
          key: *repo_cache_key
      - run:
          name: prepare environment
          command: |
            go mod download
      - save_cache:
          key: *repo_cache_key
          paths:
            - /go/pkg/mod
  test:
    executor: golang
    steps:
      - checkout
      - restore_cache:
          key: *repo_cache_key
      - run:
          name: Run linters and unit-tests
          command: |
            go get -u golang.org/x/tools/cmd/goimports
            go get -u golang.org/x/lint/golint
            sudo apt-get install python3.7 python3-pip
            pip3 install invoke
            inv test
  build:
    executor: golang
    steps:
      - checkout
      - restore_cache:
          key: *repo_cache_key
      - run:
          name: Build the artifact
          command: |
            sudo apt-get install python3.7 python3-pip
            pip3 install invoke
            inv dist
  publish:
    executor: golang
    steps:
      - checkout
      - restore_cache:
          key: *repo_cache_key
      - run:
          name: Build the artifacts for all the selected architectures and published a new GitHub release
          command: |
            sudo apt-get install python3.7 python3-pip
            pip3 install invoke
            inv release

workflows:
  version: 2
  gates:
    jobs:
      - prepare:
          filters:
            tags:
              only: /.*/
      - test:
          requires:
            - prepare
          filters:
            tags:
              only: /.*/
      - build:
          requires:
            - prepare
          filters:
            tags:
              only: /.*/
      - publish:
          requires:
            - test
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
