version: 2.1

working_directory: &working_directory
  ~/project

executors:
  golang:
    docker:
      - image: circleci/golang:1.13-buster
    working_directory: *working_directory

repo_cache_key: &repo_cache_key
  go-mod-{{ checksum "go.sum" }}.0

install_keeparelease: &install_keeparelease
  name: Install keeparelease
  command: |
    export BIN_DIR=/home/circleci/.local/bin/
    mkdir -p "${BIN_DIR}"
    export KEEPARELEASE_VERSION=1.2.1
    export KEEPARELEASE_BIN="keeparelease-${KEEPARELEASE_VERSION}-linux-amd64"
    curl -sLO "https://github.com/rgreinho/keeparelease/releases/download/${KEEPARELEASE_VERSION}/${KEEPARELEASE_BIN}"
    chmod a+x "${KEEPARELEASE_BIN}"
    mv "${KEEPARELEASE_BIN}" "${BIN_DIR}/keeparelease"

install_mage: &install_mage
  name: Install mage
  command: |
    export BIN_DIR=/home/circleci/.local/bin/
    mkdir -p "${BIN_DIR}"
    export MAGE_VERSION=1.9.0
    export MAGE_TAR="mage_${MAGE_VERSION}_Linux-64bit.tar.gz"
    curl -sLO "https://github.com/magefile/mage/releases/download/v${MAGE_VERSION}/${MAGE_TAR}"
    tar xf "${MAGE_TAR}"
    mv mage "${BIN_DIR}/"

jobs:
  prepare:
    executor: golang
    steps:
      - checkout
      - restore_cache:
          key: *repo_cache_key
      - run:
          name: prepare environment
          command: |
            go mod download
      - save_cache:
          key: *repo_cache_key
          paths:
            - /go/pkg/mod
  ci:
    executor: golang
    steps:
      - checkout
      - restore_cache:
          key: *repo_cache_key
      - run:
          <<: *install_mage
      - run:
          name: Run linters and unit-tests
          command: |
            go get -u golang.org/x/tools/cmd/goimports
            go get -u golang.org/x/lint/golint
            curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.21.0
            mage ci
  build:
    executor: golang
    steps:
      - checkout
      - restore_cache:
          key: *repo_cache_key
      - run:
          <<: *install_mage
      - run:
          name: Build the artifact
          command: |
            mage -v dist
            ls -lh dist
      - persist_to_workspace:
          root: *working_directory
          paths:
            - dist

  publish:
    executor: golang
    steps:
      - checkout
      - restore_cache:
          key: *repo_cache_key
      - run:
          <<: *install_mage
      - run:
          <<: *install_keeparelease
      - run:
          name: Build the artifacts for all the selected architectures and published a new GitHub release
          command: mage -v release

workflows:
  version: 2
  gates:
    jobs:
      - prepare:
          filters:
            tags:
              only: /.*/
      - ci:
          requires:
            - prepare
          filters:
            tags:
              only: /.*/
      - build:
          requires:
            - prepare
          filters:
            tags:
              only: /.*/
      - publish:
          requires:
            - ci
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
